### ISSUE TITLE
Axios.get have 401 on the Webstrates.ucsd.edu because the req does not include the auth

### ISSUE THREAD

**Issue by XavierXinweiWang** [madebyafox/CognitiveCanvas-Container#28]
Tried several forms of Axios req referred in https://github.com/axios/axios/issues/642

Still 401. Cannot diagnose whether the issue reside in Axios or the OPTION thing mentioned in the thread above.

**Comment by stezh** [comment]
I think this should be able to solve the issue

https://stackoverflow.com/questions/44072750/how-to-send-basic-auth-with-axios

We will use basic auth, but webstrate also support OAuth2, might be a safer choice.

**Comment by stezh** [comment]
Solved using fetch
