### ISSUE TITLE
"TODO how to add localUser's email to the map"

### ISSUE THREAD

**Issue by XavierXinweiWang** [madebyafox/CognitiveCanvas-Container#29]
Syncing map info back to MongoDB.

I think we need to figure out how (which and how to form the obj so that the map management can get and render the maps smoothly?) to sync it back. --Xavier

**Comment by stezh** [comment]
Seems like the description of this issue is about sync map back to database... what is the title about?

**Comment by mt3p** [comment]
That's just a comment I added since I wanted the user's email find the the user and update their map_ids. I'm not sure how to sync the map_ids to the user.
